### ISSUE TITLE
Set --text-accent-hover

### ISSUE THREAD

**Issue by jakobo** [seanwcom/Red-Graphite-for-Obsidian#17]
Related to #14, the text accent color (inline links) should also reflect the hover style for interactive elements. I have a local snip with this change which seems to work.

```css
.theme-light {
  --text-accent-hover: rgb(151, 46, 43);
}

.theme-dark {
  --text-accent-hover: rgb(24, 147, 242);
}
```
