### ISSUE TITLE
tree view style bug in Obsidian 1.3.5

### ISSUE THREAD

**Issue by wzh-mei** [seanwcom/Red-Graphite-for-Obsidian#27]
![image](https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/86994874/6c1d29d8-ad8f-4ce7-9fb1-09e20baff693)
After upgrading to version 1.3.5, the collapse icon is no longer aligned with the indent line, and its padding-left has bugs.

After changing the fonts, the issue remains, so I think it is not related with font.

**Comment by joegibbbon** [comment]
I've had the same issue, however, it only happens when in light mode

**Comment by wzh-mei** [comment]
provide a temporary dirty fix:
1. add a css snippet named "fix_ob_rg_light_1.3.5.css" on `value/.obsidian/snippets`, copy following code to it and save
```css
.theme-light .nav-file-title {
    padding: var(--nav-item-padding);
}
.theme-light {
  --nav-item-padding: var(--size-4-1) var(--size-4-2) var(--size-4-1) var(--size-4-6);
}
```
2. enable it on Options->Appearance->Css snippets

Not fully tested, doesn't find any side effects currently.
