### ISSUE TITLE
Solution for text color blended with the background color

### ISSUE THREAD

**Issue by CyberFicus** [seanwcom/Red-Graphite-for-Obsidian#29]
The issue: same color for text and background in search suggestions window
![image](https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/90929665/76cd9727-fd35-4c82-a567-8a018738d5a5)

The solution example code provided by sailKite at the Obsidian discord server

```css
/* for coloring the colon and text before it, as well as the search box title */
body:has(.workspace-tab-header:is(.is-active, .mod-active)[data-type*="graph"]) .suggestion-container .suggestion-item {
    color: red;
}
/* for coloring text after the colon */
body:has(.workspace-tab-header:is(.is-active, .mod-active)[data-type*="graph"]) .suggestion-container .search-suggest-info-text {
    color: blue;
}
```

Result:
![image](https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/90929665/4986f382-f3d2-4c84-bbef-fd0136521fd9)
![image](https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/90929665/3dd1101d-2468-4f62-8d55-2aa0073d9ce7)
