### ISSUE TITLE
Temporary fix for scroll bar background color in light mode

### ISSUE THREAD

**Issue by ALonelySheep** [seanwcom/Red-Graphite-for-Obsidian#36]
For some reason the scroll bar for the file index is light-colored. Here is a temporary fix which can be added as a snippet.

```css
/* Fix left side scroll bar background color */

/* WebKit Browsers */
.search-result-container::-webkit-scrollbar,
.tag-container::-webkit-scrollbar,
.suggestion::-webkit-scrollbar,
.nav-files-container::-webkit-scrollbar,
.vertical-tab-header::-webkit-scrollbar {
  width: 8px; /* Set a consistent width for better visibility and centering */
}

.search-result-container::-webkit-scrollbar-track,
.tag-container::-webkit-scrollbar-track,
.suggestion::-webkit-scrollbar-track,
.nav-files-container::-webkit-scrollbar-track,
.vertical-tab-header::-webkit-scrollbar-track {
  background: var(--color-base-100); /* Track background color */
}

.search-result-container::-webkit-scrollbar-thumb,
.tag-container::-webkit-scrollbar-thumb,
.suggestion::-webkit-scrollbar-thumb,
.nav-files-container::-webkit-scrollbar-thumb,
.vertical-tab-header::-webkit-scrollbar-thumb {
  background: var(--color-base-70); /* Thumb background color */
  border-radius: 6px; /* Rounded corners for the thumb */
}

.search-result-container::-webkit-scrollbar-thumb:hover,
.tag-container::-webkit-scrollbar-thumb:hover,
.suggestion::-webkit-scrollbar-thumb:hover,
.nav-files-container::-webkit-scrollbar-thumb:hover,
.vertical-tab-header::-webkit-scrollbar-thumb:hover {
  background: var(--color-base-50); /* Hover background color for the thumb */
}
```
