### ISSUE TITLE
Dataview fields has wrong color

### ISSUE THREAD

**Issue by phantamoe** [seanwcom/Red-Graphite-for-Obsidian#39]
![Image](https://github.com/user-attachments/assets/90932b99-7109-4585-9fe8-dc69caded6c9)

It seems that the inline fields in dataview are no longer rendered in a color that is readable both in light and dark mode

**Comment by phantamoe** [comment]
```css
.dataview.inline-field-value {
  color: white  !important;
}

.dataview.inline-field-key{
  color: white !important;
}
```

Adding the CSS above fix the problem at least in darkmode

**Comment by josephholsten** [comment]
Looks great, but has the opposite problem (whiteout) in light mode. How does this feel?

```css
.theme-dark .dataview.inline-field-value {
  color: white  !important;
}

.theme-dark .dataview.inline-field-key{
  color: white !important;
}

.theme-light .dataview.inline-field-value {
  color: black  !important;
}

.theme-light .dataview.inline-field-key{
  color: black !important;
}
```

If good, can we add that to mainline? I really don't feel confident I grok what's happening in `src/scss/index.scss`, would it make sense to add a new src/scss/app/dataview.scss with something like:

```scss
.theme-light .dataview.inline-field-key {
  color: var(--color-base-40);
}
.theme-dark .dataview.inline-field-key {
  color: var(--color-base-95);
}
```

I'm not sure how to do local dev for obsidian themes, do you just throw `sass --watch` at it while in snippets?
